### ISSUE TITLE
Open api spec/swagger

### ISSUE THREAD

**Issue by joshi-mohit** [OWASP/OWASP-VWAD#116]
Is there a way to figure out which all if these have open api spec available?

**Comment by bkimminich** [comment]
That seems entirely out of scope for VWAD as a mere inventory of vulnerable applications. If known, we provide the technology stack for each application, but not the usage of specific frameworks or components under the hood.

**Comment by joshi-mohit** [comment]
Thanks for the response.
I agree that may seem to be not be directly relevant. But if the open api spec is available for these applications, it may help it automating some tests and integrating these with open source tools which taking spec as an input and generate fuzzed traffic

Thanx
Mohit
...Happiness keeps u Sweet, Trials keep u Strong, Sorrow keeps u Human, Failure Keeps u Humble, Success keeps u Glowing, But only God Keeps u Going.....
________________________________

**Comment by kingthorin** [comment]
If it was advertised/known it could be included in the tech set. I’ll leave this open and try gathering some info at some point.

**Comment by bkimminich** [comment]
How about having an optional field on intended use or target audience? Could help distinguish between just humans or tools or even different types of tools like fuzzers, DAST or SAST?

**Comment by kingthorin** [comment]
I think we can close this. It should be included in tech set where known, I intend to do a review in the somewhat near future and will be sure to keep an eye out for this detail. (Sadly many vuln apps barely say anything about their tech set beyond things like: mean stack, php, .Net… very high level things)
