### ISSUE TITLE
Add Damn Vulnerable GraphQL Application

### ISSUE THREAD

**Issue by kingthorin** [OWASP/OWASP-VWAD#119]
- https://twitter.com/clintgibler/status/1364274041801093120
- https://github.com/dolevf/Damn-Vulnerable-GraphQL-Application

**Comment by dolevf** [comment]
Hello! I'm the creator. This has already been merged https://github.com/OWASP/OWASP-VWAD/pull/118 

Thanks for your awesome support

**Comment by kingthorin** [comment]
Oh cool, thanks. I had searched quickly but maybe I typo'd.
