### ISSUE TITLE
Use any other data format than TSV

### ISSUE THREAD

**Issue by bkimminich** [OWASP/OWASP-VWAD#16]
_As an_ occasional editor of the VWAD
_I want_ to be able to edit in the GitHub web interface
_and_ after checkout in a tool as simple as a text editor
_so that_ the file format is not regularly broken after even the simplest change.

![image](https://cloud.githubusercontent.com/assets/3531020/21539236/36432c54-cda5-11e6-9da1-6e1bca96031e.png)

> `TSV` is not exactly a file format that would make this user story possible... :smiling_imp:

**Comment by bkimminich** [comment]
Example for a "fix TSV" commit that shouldn't be necessary: d7fc49ff5ce60b41e6b78b0f511277bcfe77cefe
(used Notepad++ in the end to "hunt down" the missing tabstops...)

**Comment by psiinon** [comment]
What format do you suggest? :)
The current setup is very clunky, so alternative suggestions gratefully received.

**Comment by bkimminich** [comment]
```json
{
  "offline": [
    {
      "name": "hackxor",
      "url": "http://hackxor.sourceforge.net/cgi-bin/index.pl",
      "notes": "First 2 levels online, rest offline"
    },
    {
      "name": "Juice Shop",
      "url": "https://www.owasp.org/index.php/OWASP_Juice_Shop_Project",
      "technology": "Node/JS",
      "author": "OWASP",
      "links": {
        "download": "https://github.com/bkimminich/juice-shop",
        "docker": "https://hub.docker.com/r/bkimminich/juice-shop/",
        "guide": "https://www.gitbook.com/book/bkimminich/pwning-owasp-juice-shop"
      }
    }
  ]
}
```

**Comment by raulsiles** [comment]
I agree we need to improve the format, and also the migration/conversion between the data available in GitHub (raw files) and the OWASP Wiki for the project. I get crazy every time I have to add entries one way or the other ;) Definitely, suggestions for both are welcomed (see issue #17).

I like the suggested JSON format, to avoid dealing with spaces and tabs in TSV. Depending on the new conversion process to the OWASP Wiki, we might need to include all the fields for every new entry, or set a default (e.g. empty value) if the field does not exist for an entry.

I vote for a single place to put the data into, probably GitHub, linked from OWASP Wiki (then, we can promote it as an awesome list too).

**Comment by psiinon** [comment]
I'm good with that format, but cant see myself finding time to update the scripts anytime soon :/
I like the idea of using GitHub pages but think we probably still have to have to data on the OWASP site too as per #17
