### ISSUE TITLE
Check/Add Bonkers About Tech lists entries

### ISSUE THREAD

**Issue by kingthorin** [OWASP/OWASP-VWAD#26]
Per discussion elsewhere, ensure all of these are covered/added:
https://www.bonkersabouttech.com/security/40-intentionally-vulnerable-websites-to-practice-your-hacking-skills/392

**Comment by jhaddix** [comment]
I've had a hard time lately with the scope of the directory. In my fork I am considering splitting out all mobile/IoT/++ from the main lists. Do you all foresee those categories existing in this list or somewhere else?

**Comment by raulsiles** [comment]
Just to clarify it, OWASP DVWA main focus is to reference vulnerable web applications for testing and learning. Other vulnerable apps or software not specifically web related, such as vulnerable mobile apps, IoT enviroments, or generic vulnerable network or CtF-related labs or environments are out of the scope of OWASP DVWA.

**Comment by bkimminich** [comment]
I'm with @raulsiles that mixing other app types into VWAD (not DVWA 😉) wouldn't be a good idea. There's other more generic security-lists on GitHub already for broader overview. Let's stay focused on web here.

**Comment by raulsiles** [comment]
As we have not heard any other related arguments in favor of non-web apps included into VWAD (not DVWA :-), I'm closing this issue. It can be reopened if needed.
