### ISSUE TITLE
JSON format change of "References" String into Array

### ISSUE THREAD

**Issue by bkimminich** [OWASP/OWASP-VWAD#40]
Would anyone mind if I change the `References` property to an `Array`? 

My proposal is to change
```
"References": "https://github.com/bkimminich/juice-shop https://hub.docker.com/r/bkimminich/juice-shop/ https://www.gitbook.com/book/bkimminich/pwning-owasp-juice-shop"
```
into
```
"References": [
  "https://github.com/bkimminich/juice-shop",
  "https://hub.docker.com/r/bkimminich/juice-shop/",
  "https://www.gitbook.com/book/bkimminich/pwning-owasp-juice-shop"
]
```

Furthermore, right now JSON would suffer from information loss compared with the `TSV` format, as it does not have the link labels at the moment. So, we might go one step further and make it

```
"References": [
  {"Name": "download", "URL": "https://github.com/bkimminich/juice-shop"},
  {"Name": "docker", "URL": "https://hub.docker.com/r/bkimminich/juice-shop/"},
  {"Name": "guide", "URL": "https://www.gitbook.com/book/bkimminich/pwning-owasp-juice-shop"}
]
```

**Comment by raulsiles** [comment]
Hi Björn,
Definitely, go for it. I think the best option would be your last proposal, not to loose the context/label for each link.

Thanks!
--
Raul

**Comment by psiinon** [comment]
+1

**Comment by bkimminich** [comment]
I would also recommend to go for lower case in the property names. Starting with capital letter looks weird in JSON.

**Comment by raulsiles** [comment]
+1

**Comment by kingthorin** [comment]
+1

**Comment by kingthorin** [comment]
I might try to tackle at least part of this over lunch sometime soon. I’m leaning toward your second example.
