### ISSUE TITLE
Add, Hack the Box and PentesterLab to "Online" section

### ISSUE THREAD

**Issue by jhaddix** [OWASP/OWASP-VWAD#43]
- https://www.hackthebox.eu/
- https://pentesterlab.com/

Both excellent training grounds.

**Comment by jhaddix** [comment]
Added via https://github.com/OWASP/OWASP-VWAD/pull/47

**Comment by raulsiles** [comment]
Hi @jhaddix,
My main concern about adding these two is that they are more related to general pen-testing/hacking labs or environments (of whcih there are much more in the industry, and we do not include them here), and not specific vulnerable web applications, which is the focus of the OWASP VWAD.

Thoughts?

**Comment by bkimminich** [comment]
I would not add them here, for exactly the reason you mentioned.

**Comment by raulsiles** [comment]
Consensus :) Sorry @jhaddix, but we will not include them into VWAD.

**Comment by jhaddix** [comment]
I might say that about hackthebox, but PentesterLab has a heavy focus on web applications and is one of the most well produced boot2root resources for web app hacking learning.
