### ISSUE TITLE
Link to openhub.net via homepage is broken

### ISSUE THREAD

**Issue by RickTorresJr** [OWASP/OWASP-VWAD#49]
When browsing https://www.owasp.org/index.php/OWASP_Vulnerable_Web_Applications_Directory_Project clicking the Open Hub URL https://www.openhub.net/p/OWASP-VWAD results in "Something seems wrong with your URL".

**Comment by bkimminich** [comment]
Works for me, maybe a hickup on OpenHub's end.

**Comment by RickTorresJr** [comment]
Confirmed working now. Thanks.
