### ISSUE TITLE
Broken link to Presentation

### ISSUE THREAD

**Issue by RickTorresJr** [OWASP/OWASP-VWAD#50]
When browsing https://www.owasp.org/index.php/OWASP_Vulnerable_Web_Applications_Directory_Project the Interview with Simon Bennetts – The OWASP Web Applications Vulnerability Project http://www.trustedsoftwarealliance.com/ returns "Error establishing a database connection".

**Comment by bkimminich** [comment]
I tried to find this Podcast online elsewhere but couldn't. It's supposed to be from AppSec USA 2013, but seems not to be in the OWASP 24/7 playlist. @psiinon, do you know any other place where this might be still hosted?

**Comment by psiinon** [comment]
No I dont :/ I've emailed Mark Miller about it, as I think thats his site, or at least one he's closely associated with

**Comment by psiinon** [comment]
Mark has replied - direct link is https://soundcloud.com/trustedsoftwarealliance/simon-bennetts-web :)

**Comment by psiinon** [comment]
Updated on the OWASP wiki - thanks for letting us know about this @RickTorresJr :)
