### ISSUE TITLE
Add www.webscantest.com to the online list

### ISSUE THREAD

**Issue by raulsiles** [OWASP/OWASP-VWAD#51]
By Rapid7 appspider: http://www.webscantest.com

**Comment by psiinon** [comment]
Its already on https://www.owasp.org/index.php/OWASP_Vulnerable_Web_Applications_Directory_Project#tab=On-Line_apps :)
3rd from the bottom

**Comment by raulsiles** [comment]
Thanks Simon.

Ups :(, I run a search at https://github.com/OWASP/OWASP-VWAD/blob/master/src/owasp-wiki/online.json and didn't find it, although it is in fact there :) I need to improve my search capabilities.

Closing this issue after updating the author (https://github.com/OWASP/OWASP-VWAD/commit/5032682e84e6a4dc0a5be0a20ab1f0e5591e469d)
