### ISSUE TITLE
Add DVSA

### ISSUE THREAD

**Issue by kingthorin** [OWASP/OWASP-VWAD#55]
- https://mobile.twitter.com/DVSAowasp/status/1078008081177559042
- http://serverless.fail

![image](https://user-images.githubusercontent.com/7570458/50784646-3d960f80-127c-11e9-90ba-1c6c0f5222c3.png)

**Comment by kingthorin** [comment]
https://github.com/OWASP/DVSA/tree/master/AWS/LESSONS

**Comment by raulsiles** [comment]
https://www.owasp.org/index.php/OWASP_DVSA
