### ISSUE TITLE
Update Webgoat.NET

### ISSUE THREAD

**Issue by kingthorin** [OWASP/OWASP-VWAD#68]
Per OWASP Slack:
> @kingthorin_rm there’s two versions of WebGoat.NET - jerryhoff hasn’t been updated since 2014, but there is also one that’s 2018 - https://github.com/rapPayne/WebGoat.Net

Entry should probably be updated something like:

```json
	{
		"url": "https://github.com/rapPayne/WebGoat.Net",
		"name": ".NET Goat",
		"technology": [
			"C#"
		],
		"references": [
			{
				"name": "download",
				"url": "https://github.com/rapPayne/WebGoat.Net"
			},
			{
				"name": "download",
				"url": "http://github.com/jerryhoff/WebGoat.NET"
			}
		],
		"author": "OWASP",
		"notes": null
	}
```

**Comment by bkimminich** [comment]
If we believe the README of the newer one, that's the official from OWASP and therefore should be the only link, no? Having abandoned vuln apps in the inventory is fine, but why keep track of dead branches?

**Comment by bkimminich** [comment]
To make things worse: https://github.com/jowasp/WebGoat.NET

**Comment by kingthorin** [comment]
Ya, I'm in the process of posting to the Leaders group about it. Talk about confusing :-1: 

Unfortunately I suspect there's no good solution/answer.

**Comment by bkimminich** [comment]
I fully share your suspicion... :-) ... previous attempts to clean up even inside the OWASP org on GitHub have not exactly been blessed with success... ;-)

**Comment by kingthorin** [comment]
Maybe instead of having the older one as a download reference I’d put a note including the URL in the notes field. Ex: “Original main repo: ...”
