### ISSUE TITLE
Add Andro Goat (and new "Mobile" category)

### ISSUE THREAD

**Issue by bkimminich** [OWASP/OWASP-VWAD#70]
https://github.com/satishpatnayak/AndroGoat

As OWASP has many mobile related projects by now, giving mobile vuln apps their own category in here seems reasonable, doesn't it?

As a fallback it could be added to "Offline" first and we only add a new "Mobile" category once we find a couple more candidates.

**Comment by raulsiles** [comment]
I would prefer not to add a mobile category and the associated vulnerable mobile apps. The project is focused just on web apps (hence the name and acronym, VWAD project), but I'm open to hear other project members comments.

Perhaps we should create a new OWASP-VMAD project, OWASP Vulnerable Mobile Applications Directory project? Thoughts?

**Comment by bkimminich** [comment]
Well the "W" in OWASP is for "Web" but there's tons of Mobile Projects, no? With little in number a separate project for the mobile vuln apps feels a bit like overkill.

**Comment by raulsiles** [comment]
Definitely, I agree with the "W" in the OWASP acronym, but if OWASP would have known that in the future it was going to focus in mobile, and IoT, and... (who knows), apart from web apps, I'm sure the name would have been a different one. 

Unfortunately, OWASP cannot change its name at this point, although it can change (or broad) its focus. For VWAD we do not have that limitation and I think there is an option to select another name for a different project, if it is well worth. There is a bunch of vulnerable mobile apps available for testing and training and challenging people... not only from OWASP, that could be included in that potential directory...

**Comment by bkimminich** [comment]
How about renaming the VWAD into VAD? Then it'd remain one directory. But if course a separate one under the Mobile Security Project ☂️ would also work. I just don't see value in having something spawn and then end up ill maintained whereas keeping it inside an existing working project would have been an easy alternative.

**Comment by kingthorin** [comment]
Given the sheer number of mobile apps that are web enabled in one way or another (or many)  I think it's fine to include a new category.

@psiinon thoughts?

**Comment by psiinon** [comment]
Surely mobile apps use the web? :) I still think they fit under VWAD but v happy to have a new mobile category.
Not sure we need to rename to VAD but dont hate that idea either, just seems a bit unnessessary to me...

**Comment by commjoen** [comment]
We actually have quite some mobile apps: see https://github.com/OWASP/owasp-mstg/blob/master/Document/0x08-Testing-Tools.md#vulnerable-applications for instance...
